name: accelerometer_example
description: Demonstrates how to use the accelerometer plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  syncfusion_flutter_gauges: ^28.2.12
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  smart_accelerometer:
    path: ../

flutter:

  uses-material-design: true


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/accelerometer.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/accelerometer.png"
  background_color: "#FFFFFF"
  theme_color: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/images/accelerometer.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/accelerometer.png"
    icon_size: 48 

  macos:
    generate: true
    image_path: "assets/images/accelerometer.png"

flutter_native_splash:
  image: assets/images/accelerometer.png
  color: "#FFFFFF"  
  android: true
  ios: true
  web: true


